font_family AdwaitaMono Nerd Font Mono
font_size 13

disable_ligatures no
enable_audio_bell no

remember_window_size no
initial_window_width 640
initial_window_height 480
window_padding_width 2

background_opacity 0.80
scrollbar_handle_opacity 0
scrollbar_track_opacity 0
scrollbar_track_hover_opacity 0
confirm_os_window_close 0

sync_to_monitor no

#######
#THEME#-->Apprentice.conf (https://github.com/dexpota/kitty-themes/blob/master/themes/Apprentice.conf)
#######

cursor     #c7c7c7
cursor_text_color #feffff
selection_foreground #3e3e3e
selection_background #c1ddff
foreground #c8c8c8
background #323232
color0     #252525
color8     #555555
color1     #be7472
color9     #ff9900
color2     #709772
color10    #97bb98
color3     #989772
color11    #fefdbc
color4     #7199bc
color12    #9fbdde
color5     #727399
color13    #989abc
color6     #719899
color14    #6fbbbc
color7     #7f7f7f
color15    #feffff